### ISSUE TITLE
cooldatasets.com no longer online

### ISSUE THREAD

**Issue by bbrewington** [awesomedata/apd-core#281]
in apd-core:
https://github.com/awesomedata/apd-core/blob/2aebaecfd748904c8b1014dcfa1b84d11f137ac5/deploy/index.mako#L78

added to awesome-public-datasets in this commit:
https://github.com/awesomedata/awesome-public-datasets/commit/dc1f51b3263d700596603c4a52c54dd9b44d0955

Here's last valid copy in Internet Archive:
https://web.archive.org/web/20200106113005/https://cooldatasets.com/

**Comment by bbrewington** [comment]
I think this is no longer a valid entry - https://twitter.com/cooldatasets says "This account no longer exists"

**Comment by ppival** [comment]
Thanks, and apologies for the delay - this has been updated along with some other commits, @bbrewington
